### ISSUE TITLE
使用七牛来CDN 来加速论坛的访问速度

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/discourse#2]

**Comment by zilongshanren** [comment]
参考链接： 
1. http://jingyan.baidu.com/article/ce09321b54cb672bff858fb4.html
2. http://www.freehao123.com/discourse-cdn-ssl/

**Comment by xuchunyang** [comment]
我刚刚用 Google 的 PageSpeed 测试了下网站，得分是 67/100，好像有一个图片（很可能是网站的 Logo）过大，有压缩的空间。

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Femacs-china.org%2F&tab=desktop

**Comment by zilongshanren** [comment]
@li-xinyang  网站 logo 你能否压缩一下再上传一个?

**Comment by ghost** [comment]
已经将最大的 Logo 缩放尺寸并无损压缩，现在只需 34 KB。

**Comment by xuchunyang** [comment]
关闭。理由见：https://emacs-china.org/t/https/183
