### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/discourse#5]
现在网站通常默认用 HTTPS 了，虽然我对安全和隐私并不敏感，正常的使用互联网对我（中国人）来说还很成问题。

（这事情的优先级可以比较低，我只是不想老惦记这事）

**Comment by zilongshanren** [comment]
@xuchunyang 

这个我周末加上 https 的支持，这个是很有必要的。

**Comment by zilongshanren** [comment]
https://gaudettetim.wordpress.com/2015/12/19/ssl-for-discourse-with-lets-encrypt/

**Comment by zilongshanren** [comment]
https://meta.discourse.org/t/setting-up-lets-encrypt-cert-with-discourse-docker/40709

**Comment by zilongshanren** [comment]
目前已经支持。

**Comment by xuchunyang** [comment]
@zilongshanren 现在 https://emacs-china.org/ 没法访问了

**Comment by zilongshanren** [comment]
@xuchunyang 再试试？刚刚我在调整。

**Comment by xuchunyang** [comment]
现在可以连上了。昨天我也遇到过一次无法连接，也是很快就又好了。

**Comment by zilongshanren** [comment]
@xuchunyang 很可能当时是我在操作网站。。。

**Comment by zilongshanren** [comment]
@xuchunyang  网站暂时不折腾了，目前的状态我还挺满意的。我专注把 21 天系列做好。
