### ISSUE TITLE
“站点反馈”这个页面不存在

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/discourse#6]
页面链接是：http://emacs-china.org/c/site-feedback
我在 http://emacs-china.org/faq#power 部分发现的这个链接。

可以考虑把这个链接移除，或者新建一个 site-feedback 的类别。

**Comment by qinshulei** [comment]
应该是把链接修正到社区建设吧.

**Comment by xuchunyang** [comment]
好，已经修复了。

**Comment by zilongshanren** [comment]
@xuchunyang  我把该主题置顶了，并且取消了 只有管理员才能观看的限制。不过暂时没有找到 如何禁止跟帖。
