### ISSUE TITLE
把 ELPA 镜像的地址加到社区顶部

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/discourse#7]
继续 https://github.com/emacs-china/elpa/issues/12 中的讨论

导航栏的效果可见：http://elpa.emacs-china.org/

**Comment by xuchunyang** [comment]
我已经添加了，顺便把 About 和 EGO 的链接去掉了，因为，
- [About](http://about.emacs-china.org/) 页面提供的信息在目前的导航栏中已经体现出来了
- EGO （一个静态网页生成器）对一般 Emacs 用户意义不大。把每一个 Emacs China 下的 Emacs Package 都放到导航栏上也不现实。

**Comment by zilongshanren** [comment]
@xuchunyang 
不过论坛的首页还显示一个 Forum 的链接挺奇怪的。。。 About 页面主要是有一些关键信息，比如“让 Emacs 在中国流行起来” 没有体现。。。

另外，About 和 EGO 是历史融合产物，建议保留一段时间。

**Comment by xuchunyang** [comment]
> 不过论坛的首页还显示一个 Forum 的链接挺奇怪的。。。

在我昨晚修改导航栏之前，Forum 已经在那了，不知道是谁加的。我没去掉是因为我觉得 Forum 类似于其它网站上的 首页（举个例子：http://www.qiniu.com/ ），也不是没道理。或许，加这个链接的人有更好的解释？！

**Comment by zilongshanren** [comment]
@xuchunyang 
我们的导航链接都是 popup 一个窗口，所以我觉得没啥必要。。

**Comment by qinshulei** [comment]
应该几乎所有网站都是这样的，现在需要默认标识为选中，高亮一下，表明你现在在这个栏目下。

**Comment by xuchunyang** [comment]
> 我们的导航链接都是 popup 一个窗口，所以我觉得没啥必要。。

除非不得已，没必要默认开一个新的窗口。（如果用户想开一个新的，自己动手也行，比如 Mac 上按住 CMD）
